default:
  # Use the official docker image.
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

stages:
  - dev
  - version

dev:
  stage: dev
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}_Dev" .
    - docker push "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}_Dev"
  rules:
    - if: '$CI_COMMIT_TAG =~ "/^$/"'
      exists:
        - dockerfile

version:
  stage: version
  script:
    - docker build --pull -t "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}" .
    - docker push "$CI_REGISTRY_IMAGE:${CI_COMMIT_REF_SLUG}"
  rules:
    - if: '$CI_COMMIT_TAG !~ "/^$/"'
      exists:
        - dockerfile