version: '3.4'

services:
  system_api:
    image: registry.gitlab.com/individual-projects2/container-build-management-mastering-program:v0.0.1
    restart: always
    container_name: Container-Build-Management-Mastering-Program
    ports:
      - 8080:80
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/dply/sql:/API/SQL"
      - "/var/log/dply:/API/Log"
    env_file:
      - env/.env